apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: catalyst-broker
  namespace: {{ .Values.namespace }}
spec:
  serviceName: "catalyst-broker"
  replicas: {{ .Values.mosquitto.replicas }}
  selector:
    matchLabels:
      app: catalyst-broker
  template:
    metadata:
      labels:
        app: catalyst-broker
    spec:
      containers:
        - name: mosquitto
          image: {{ .Values.mosquitto.image }}
          ports:
            - containerPort: 1883
            - containerPort: 9001
          livenessProbe:
            tcpSocket:
              port: 1883
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 1883
            initialDelaySeconds: 5
            periodSeconds: 5
          volumeMounts:
            - name: mosquitto-config
              mountPath: /mosquitto/config/mosquitto.conf
              subPath: mosquitto.conf
      volumes:
        - name: mosquitto-config
          configMap:
            name: mosquitto-config
  volumeClaimTemplates: []
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
  namespace: {{ .Values.namespace }}
data:
  mosquitto.conf: |
    listener 1883
    allow_anonymous true
    listener 9001
    protocol websockets
    allow_anonymous true
---
apiVersion: v1
kind: Service
metadata:
  name: catalyst-broker-service
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  selector:
    app: catalyst-broker
  ports:
    - name: mqtt-tcp
      port: 1883
      nodePort: {{ .Values.mosquitto.ports.nodePort }}
    - name: mqtt-ws
      port: 9001
      nodePort: 30002
