apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: catalyst-db
  namespace: {{ .Values.namespace }}
spec:
  serviceName: "catalyst-db"
  replicas: {{ .Values.postgres.replicas }}
  selector:
    matchLabels:
      app: catalyst-db
  template:
    metadata:
      labels:
        app: catalyst-db
    spec:
      containers:
        - name: postgres
          image: {{ .Values.postgres.image }}
          ports:
            - containerPort: 5432
          livenessProbe:
            exec:
              command: ["pg_isready", "-U", "{{ .Values.postgres.auth.username }}", "-d", "{{ .Values.postgres.auth.database }}"]
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "{{ .Values.postgres.auth.username }}", "-d", "{{ .Values.postgres.auth.database }}"]
            initialDelaySeconds: 5
            periodSeconds: 5
          env:
            - name: POSTGRES_USER
              value: {{ .Values.postgres.auth.username }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgres.auth.password }}
            - name: POSTGRES_DB
              value: {{ .Values.postgres.auth.database }}
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.postgres.storage }}
---
apiVersion: v1
kind: Service
metadata:
  name: catalyst-db-service
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  selector:
    app: catalyst-db
  ports:
    - port: 5432
      nodePort: {{ .Values.postgres.ports.nodePort }}
