{{- if .Values.ui.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalyst-ui
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: {{ .Values.ui.replicas }}
  selector:
    matchLabels:
      app: catalyst-ui
  template:
    metadata:
      labels:
        app: catalyst-ui
    spec:
      containers:
        - name: ui
          image: {{ .Values.ui.image }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: catalyst-ui-service
  namespace: {{ .Values.global.namespace }}
spec:
  type: {{ .Values.ui.service.type }}
  selector:
    app: catalyst-ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: {{ .Values.ui.service.nodePort }}
{{- end }}
