kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30000
        hostPort: 5432 # Postgres (NodePort 30000)
        protocol: TCP
      - containerPort: 30001
        hostPort: 1883 # MQTT TCP (NodePort 30001)
        protocol: TCP
      - containerPort: 30002
        hostPort: 9001 # MQTT WS (NodePort 30002)
        protocol: TCP
      - containerPort: 30080
        hostPort: 8081 # UI / Ingress (NodePort 30080)
        protocol: TCP
      - containerPort: 30090
        hostPort: 9090 # Prometheus (NodePort 30090)
        protocol: TCP
      - containerPort: 30030
        hostPort: 3000 # Grafana (NodePort 30030)
        protocol: TCP
