services:
  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: deleggit_broker
    ports:
      - "1883:1883" # Standard MQTT
      - "9001:9001" # WebSockets
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    restart: unless-stopped
