services:
  prometheus:
    image: prom/prometheus:latest
    container_name: catalyst-prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  grafana:
    image: grafana/grafana:latest
    container_name: catalyst-grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=catalyst
    ports:
      - "3000:3000"
